model:
  arch: see_chat

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"

  # train
  freeze_vit: True
  freeze_qformer: True

  # Q-Former
  num_query_token: 32

  # GLM
  llama_model: "../models/chatglm-6b"
  
  # generation configs
  prompt: ""

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
